#! /bin/bash

emcc -O3 \
     lib/marching-squares-wasm-api.c \
     lib/marching-squares.c \
     include/jansson-2.13.1/emcc-lib/lib/libjansson.a \
     -Iinclude/jansson-2.13.1/emcc-lib/include \
     -s EXPORTED_FUNCTIONS='["_generate_isolines_geojson_"]' \
     -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap', 'UTF8ToString']" \
     -s WASM=1 \
     -s ENVIRONMENT='web' \
     -s ALLOW_MEMORY_GROWTH=1 \
     -s NO_EXIT_RUNTIME=0 \
     -s LLD_REPORT_UNDEFINED \
     -s ASSERTIONS=1 \
     -o dist/wasm-marching-squares.js
